In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
# check CPU or GPU is available
if torch.cuda.is_available():
    print("GPU is available", torch.cuda.get_device_name(0))
else:
    print("GPU is NOT available, Using CPU")

GPU is NOT available, Using CPU


Creating Tensors

In [3]:
t = torch.empty(4,5)
t

tensor([[2.1165e-09, 4.3931e-41, 2.1165e-09, 4.3931e-41, 1.6019e-25],
        [0.0000e+00, 1.6019e-25, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
# check type
type(t)

torch.Tensor

In [5]:
torch.zeros([4,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones([2,4,5])

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [7]:
torch.rand([2,3])

tensor([[0.5823, 0.8801, 0.3922],
        [0.0975, 0.3840, 0.5346]])

In [8]:
torch.rand([2,3])

tensor([[0.8035, 0.4116, 0.2711],
        [0.8588, 0.1383, 0.3644]])

In [9]:
torch.manual_seed(1000)
torch.rand([2,3])

tensor([[0.3189, 0.6136, 0.4418],
        [0.2580, 0.2724, 0.6261]])

In [10]:
torch.manual_seed(1000)
torch.rand([2,3])

tensor([[0.3189, 0.6136, 0.4418],
        [0.2580, 0.2724, 0.6261]])

In [11]:
a = torch.tensor([1,3,4,5])
a

tensor([1, 3, 4, 5])

In [12]:
type(a)

torch.Tensor

In [13]:
# Other ways to create tensor

print("linearly spaced tensors", torch.linspace(1, 100, 10))

print("Identity Matrix", torch.eye(7,5))

print("Display tensor", torch.arange(1,100,2))

print("Create tensor of specific digit", torch.full([9,9], 24))

linearly spaced tensors tensor([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])
Identity Matrix tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Display tensor tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])
Create tensor of specific digit tensor([[24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24, 24, 24, 24,

Tensor Shape & Creating tensors using shape

In [14]:
t = torch.tensor([[4,9],[23,42],[34,78]])
t

tensor([[ 4,  9],
        [23, 42],
        [34, 78]])

In [15]:
t.shape

torch.Size([3, 2])

In [16]:
print(torch.empty_like(t))
print(torch.zeros_like(t))
print(torch.ones_like(t))

tensor([[0, 0],
        [0, 0],
        [1, 0]])
tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[1, 1],
        [1, 1],
        [1, 1]])


In [17]:
print(torch.rand_like(t))  #we need to define data type of tensor

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

Tensor Data types

In [18]:
t.dtype

torch.int64

In [19]:
# creating tensor using int data type
t1 = torch.tensor([1.2,3.4,5.6,5.6], dtype=torch.int32)
t1

tensor([1, 3, 5, 5], dtype=torch.int32)

In [20]:
# creating tensor using float data type
torch.tensor([1, 3, 5, 5], dtype=torch.float32)

tensor([1., 3., 5., 5.])

In [21]:
# converting data type of tensor using to()
t1.to(torch.float32)

tensor([1., 3., 5., 5.])

In [22]:
print(torch.rand_like(t, dtype=torch.float32))  # resolved error

tensor([[0.4410, 0.3653],
        [0.3535, 0.5971],
        [0.3572, 0.4807]])


Mathematical operations on tensor

In [23]:
# add
print(t1 + 24)
# sub
print(t1 - 24)
# mul
print(t1 * 24)
# int divide
print(t1 // 4)
# divide
print(t1 / 4)
# mod
print(t1 % 2)
# power
print(t1 ** 9)

tensor([25, 27, 29, 29], dtype=torch.int32)
tensor([-23, -21, -19, -19], dtype=torch.int32)
tensor([ 24,  72, 120, 120], dtype=torch.int32)
tensor([0, 0, 1, 1], dtype=torch.int32)
tensor([0.2500, 0.7500, 1.2500, 1.2500])
tensor([1, 1, 1, 1], dtype=torch.int32)
tensor([      1,   19683, 1953125, 1953125], dtype=torch.int32)


Element wise operation

In [24]:
a = torch.tensor([2,3,43,54])
b = torch.tensor([45,87,32,4])

print(a)
print(b)

tensor([ 2,  3, 43, 54])
tensor([45, 87, 32,  4])


In [25]:
print(a+b)
print(a-b)
print(a//b)
print(a/b)
print(a*b)
print(a%b)
print(a**b)

tensor([47, 90, 75, 58])
tensor([-43, -84,  11,  50])
tensor([ 0,  0,  1, 13])
tensor([ 0.0444,  0.0345,  1.3438, 13.5000])
tensor([  90,  261, 1376,  216])
tensor([ 2,  3, 11,  2])
tensor([      35184372088832,  7352787613788948299, -5402179514034286207,
                     8503056])


In [26]:
c = torch.tensor([2,3,4,5,-2,-2,-3,-2])
# absolute value
print(c.abs())
# negative value ans vice versa
print(c.neg())

tensor([2, 3, 4, 5, 2, 2, 3, 2])
tensor([-2, -3, -4, -5,  2,  2,  3,  2])


In [27]:
data = torch.tensor([1.9, 2.3, 3.7, 4.4])
data

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [28]:
print(data.round())
print(data.ceil())
print(data.floor())
print(data.clamp(min=1, max=2))

tensor([2., 2., 4., 4.])
tensor([2., 3., 4., 5.])
tensor([1., 2., 3., 4.])
tensor([1.9000, 2.0000, 2.0000, 2.0000])


Reduction operation

In [29]:
data2 = torch.randint(low=9, high=24, size=(2,3), dtype=torch.float32)
data2

tensor([[18., 17., 18.],
        [12., 14., 18.]])

In [30]:
# sum
print(torch.sum(data2))

# row sum
print(torch.sum(data2, dim=1))

# column sum
print(torch.sum(data2, dim=0))

tensor(97.)
tensor([53., 44.])
tensor([30., 31., 36.])


In [31]:
# mean
print(torch.mean(data2))
# mean on column
print(torch.mean(data2, dim=0))
# mean on row
print(torch.mean(data2, dim=1))

tensor(16.1667)
tensor([15.0000, 15.5000, 18.0000])
tensor([17.6667, 14.6667])


In [32]:
# min
print(torch.min(data2))
# max
print(torch.max(data2))
# product
print(torch.prod(data2))
# standard deviation
print(torch.std(data2))
# variance
print(torch.var(data2))
# argmax -> position of max argument
print(torch.argmax(data2))
# argmin -> position of min argument
print(torch.argmin(data2))

tensor(12.)
tensor(18.)
tensor(16656192.)
tensor(2.5626)
tensor(6.5667)
tensor(0)
tensor(3)


Matrix multiplication

In [33]:
data3 = torch.randint(low=9, high=24, size=(2,3), dtype=torch.float32)
data4 = torch.randint(low=9, high=24, size=(3,2), dtype=torch.float32)
print(data3)
print(data4)

tensor([[21., 15., 16.],
        [17., 14., 19.]])
tensor([[21., 19.],
        [16., 16.],
        [18., 22.]])


In [34]:
data4.matmul(data3)

tensor([[764., 581., 697.],
        [608., 464., 560.],
        [752., 578., 706.]])

Dot product

In [35]:
torch.dot(torch.tensor([1,2,3,4]), torch.tensor([5,6,7,8]))

tensor(70)

In [36]:
print(data4)
print(data4.transpose(1,0))

tensor([[21., 19.],
        [16., 16.],
        [18., 22.]])
tensor([[21., 16., 18.],
        [19., 16., 22.]])


inverse

In [37]:
f = torch.randint(low=1, high=100, size=(3,3), dtype=torch.float32)
f

tensor([[81., 61.,  1.],
        [24., 81., 48.],
        [89., 50., 18.]])

In [38]:
torch.inverse(f)

tensor([[-0.0062, -0.0069,  0.0187],
        [ 0.0253,  0.0090, -0.0254],
        [-0.0396,  0.0091,  0.0335]])

determinant

In [39]:
torch.det(f)

tensor(151929.)

Comparison Operation on each element

In [40]:
t1 = torch.randint(low=1, high=100, size=(3,3), dtype=torch.float32)
t2 = torch.randint(low=1, high=100, size=(3,3), dtype=torch.float32)
print(t1)
print(t2)

tensor([[18., 21., 26.],
        [31., 87., 23.],
        [92., 58., 30.]])
tensor([[41., 21., 91.],
        [85., 85., 66.],
        [74., 93., 27.]])


In [41]:
print(t1 > t2)
print(t1 >= t2)
print(t1 < t2)
print(t1 <= t2)
print(t1 == t2)
print(t1 != t2)

tensor([[False, False, False],
        [False,  True, False],
        [ True, False,  True]])
tensor([[False,  True, False],
        [False,  True, False],
        [ True, False,  True]])
tensor([[ True, False,  True],
        [ True, False,  True],
        [False,  True, False]])
tensor([[ True,  True,  True],
        [ True, False,  True],
        [False,  True, False]])
tensor([[False,  True, False],
        [False, False, False],
        [False, False, False]])
tensor([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]])


Special operations

In [42]:
# log
print(t1.log())
# torch.log(t1)
# sqrt
print(t1.sqrt())
# exp
print(t1.exp())
# sigmoid
print(t1.sigmoid())
# softmax
print(torch.softmax(t1, dim=0))
# relu
print(torch.relu(t1))

tensor([[2.8904, 3.0445, 3.2581],
        [3.4340, 4.4659, 3.1355],
        [4.5218, 4.0604, 3.4012]])
tensor([[4.2426, 4.5826, 5.0990],
        [5.5678, 9.3274, 4.7958],
        [9.5917, 7.6158, 5.4772]])
tensor([[6.5660e+07, 1.3188e+09, 1.9573e+11],
        [2.9049e+13, 6.0760e+37, 9.7448e+09],
        [       inf, 1.5455e+25, 1.0686e+13]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[7.2813e-33, 2.1705e-29, 1.7970e-02],
        [3.2213e-27, 1.0000e+00, 8.9468e-04],
        [1.0000e+00, 2.5437e-13, 9.8114e-01]])
tensor([[18., 21., 26.],
        [31., 87., 23.],
        [92., 58., 30.]])


Inplace operation

In [43]:
tt1 = torch.randint(low=1, high=100, size=(3,3), dtype=torch.float32)
tt2 = torch.randint(low=1, high=100, size=(3,3), dtype=torch.float32)
print(tt1)
print(tt2)

tensor([[82., 37., 57.],
        [70., 12., 60.],
        [18., 93., 58.]])
tensor([[66., 92.,  7.],
        [86., 94., 30.],
        [27., 60., 68.]])


In [44]:
tt1 + tt2 #it will create new tensor

tensor([[148., 129.,  64.],
        [156., 106.,  90.],
        [ 45., 153., 126.]])

In [45]:
tt1.add_(tt2)  #result will be stored inside tt1

tensor([[148., 129.,  64.],
        [156., 106.,  90.],
        [ 45., 153., 126.]])

In [46]:
tt1

tensor([[148., 129.,  64.],
        [156., 106.,  90.],
        [ 45., 153., 126.]])

In [47]:
tt2

tensor([[66., 92.,  7.],
        [86., 94., 30.],
        [27., 60., 68.]])

Copying a tensor

In [48]:
t12 = torch.randint(low=1, high=100, size=(3,3), dtype=torch.float32)
t12

tensor([[40., 72., 71.],
        [82., 85., 36.],
        [83., 91., 76.]])

In [49]:
t22 = t12   #changes will reflected in both
t22

tensor([[40., 72., 71.],
        [82., 85., 36.],
        [83., 91., 76.]])

In [50]:
t22[0][0] = 2409
t22

tensor([[2409.,   72.,   71.],
        [  82.,   85.,   36.],
        [  83.,   91.,   76.]])

In [51]:
t12

tensor([[2409.,   72.,   71.],
        [  82.,   85.,   36.],
        [  83.,   91.,   76.]])

In [52]:
t12[0][0] = 234
t12

tensor([[234.,  72.,  71.],
        [ 82.,  85.,  36.],
        [ 83.,  91.,  76.]])

In [53]:
t22

tensor([[234.,  72.,  71.],
        [ 82.,  85.,  36.],
        [ 83.,  91.,  76.]])

In [54]:
print(id(t12))
print(id(t22))

134646979481344
134646979481344


In [55]:
t13 = t12.clone()
t13

tensor([[234.,  72.,  71.],
        [ 82.,  85.,  36.],
        [ 83.,  91.,  76.]])

In [56]:
t12[0][0] = 123
t12

tensor([[123.,  72.,  71.],
        [ 82.,  85.,  36.],
        [ 83.,  91.,  76.]])

In [57]:
t13

tensor([[234.,  72.,  71.],
        [ 82.,  85.,  36.],
        [ 83.,  91.,  76.]])

In [58]:
print(id(t12))
print(id(t13))

134646979481344
134646979491344


Tensor operation on GPU

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = torch.device('cuda')
device

device(type='cuda')

In [4]:
# creating tensor
torch.tensor([1,2,3,4,5], device=device)

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [9]:
t1 = torch.rand(2,3)
t1

tensor([[0.0140, 0.5970, 0.8795],
        [0.8157, 0.2591, 0.6027]])

In [10]:
# running existing tensors inside gpu
t1.to(device)

tensor([[0.0140, 0.5970, 0.8795],
        [0.8157, 0.2591, 0.6027]], device='cuda:0')

In [12]:
import time

size = 10000

matrix1 = torch.randn(size,size)
matrix2 = torch.randn(size,size)

# measure time on cpu
s = time.time()
result_cpu = torch.matmul(matrix1, matrix2)
e = time.time()
print(f"Total time required: {e-s} seconds")

# measure time on gpu
s = time.time()
matrix1 = matrix1.to('cuda')
matrix2 = matrix2.to('cuda')
result_cpu = torch.matmul(matrix1, matrix2)
e = time.time()
print(f"Total time required: {e-s} seconds")

Total time required: 16.635396480560303 seconds
Total time required: 0.2830469608306885 seconds


Reshape tensor

In [13]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [16]:
# flatten
a.flatten()  #single dimension

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
b = torch.rand(2,3,4)
b

tensor([[[0.9191, 0.0151, 0.3408, 0.5396],
         [0.1753, 0.0629, 0.1212, 0.1457],
         [0.5447, 0.7456, 0.6166, 0.9953]],

        [[0.3122, 0.7593, 0.6726, 0.5802],
         [0.5032, 0.7479, 0.1476, 0.1575],
         [0.4999, 0.9119, 0.9690, 0.3421]]])

In [18]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [21]:
# unsqueeze
# image size
c = torch.rand(226, 226, 3)
c.unsqueeze(1).shape
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [22]:
# squeeze
c = torch.rand(1, 20)
c.squeeze(0).shape

torch.Size([20])

Numpy and Pytorch

In [23]:
import numpy as np

In [24]:
# convert tensor to numpy array
a = torch.tensor([1,2,3,4])
a

tensor([1, 2, 3, 4])

In [25]:
type(a)

torch.Tensor

In [26]:
b = a.numpy()
type(b)

numpy.ndarray

In [27]:
c = torch.from_numpy(b)
type(c)

torch.Tensor